### ISSUE TITLE
failed to load java.lang.IllegalStateException

### ISSUE THREAD

**Issue by niemandvs** [MelanX/SkyblockBuilder#43] opened 2021-06-07 06:10 UTC
**Versions**

Minecraft: 1.16.5
Forge: 36.1.25
Skyblock Builder: skyblockbuilder-1.16.4-1.5.6.jar
Modpack: 
not release

**Describe the bug**

**How to reproduce**

1. start mod with minecraft forge version 36.1.25
2.  get error java.lang.IllegalStateException for skyblockbuilder
3. 

**Expected behavior**

**Screenshots**

[crash-2021-06-07_07.59.53-fml.txt](https://github.com/MelanX/SkyblockBuilder/files/6606261/crash-2021-06-07_07.59.53-fml.txt)

**Comment by MelanX** [comment] 2021-06-07 06:38
Please fill out everything. Otherwise I will close this.

**Comment by niemandvs** [comment] 2021-06-07 07:18
> Please fill out everything. Otherwise I will close this.

is there any info more i dont have modpack its a new creation by me to create starting island and so on

**Comment by noeppi-noeppi** [comment] 2021-06-07 07:29
The problem is that you try to delete the old config even if it does not exist. The correct approach would be to use `Files.deleteIfExists` here. Also your should not throw an exception if it fails because some operating systems prevent deletion of files that are opened in another program (which in this case could be forge having the config file open). In that case I think it would be the best to just log that deletion of the file failed and maybe display a message to the player and tell him to delete the file manually.

**Closed as completed** 2021-06-07 09:48 UTC
Labels: bug
