### ISSUE TITLE
Datapack causing world to freeze/datapack not generating structures

### ISSUE THREAD

**Issue by tmanfoo1** [MelanX/SkyblockBuilder#93] opened 2022-07-18 22:25 UTC
### Minecraft version

1.18.2

### LibX version

3.2.18

### Skyblock Builder version

3.3.23

### Forge version

40.1.68

### The latest.log file

[latest.log](https://github.com/MelanX/SkyblockBuilder/files/9136035/latest.log)

### Issue description

The generation freezes at 100% and will not allow users to join the world **[caused by lucky blocks]** / the skyblock world will not generate structures.

### Steps to reproduce

1) Navigate to the create a world screen
2) Select worldtype skyblock and ensure that the andromeda is selected
3) ensure that datapack provided is loaded
4)Generate world and you will notice that it freezes upon reaching 100%, You can often hear the world around you after waiting a wile, but the screen is never exited and remains frozen.

 [this is the test pack I am using without lucky blocks for proof that my structures are not generating]
[skyblock testing-horriblebadtime.zip](https://github.com/MelanX/SkyblockBuilder/files/9136638/skyblock.testing-horriblebadtime.zip)

**Comment by tmanfoo1** [comment] 2022-07-18 23:18
[Andromeda Automation-3.2.zip](https://github.com/MelanX/SkyblockBuilder/files/9136210/Andromeda.Automation-3.2.zip)
I know you dont want this but its moreso for me. 
Additionally my structures still do not generate in the world

**Comment by tmanfoo1** [comment] 2022-07-18 23:30
Update!!! it seems like lucky block is causing the issue of it not loaded
HOWEVER the structures still are not generating

**Comment by tmanfoo1** [comment] 2022-07-18 23:41
[skyblock testing-horriblebadtime.zip](https://github.com/MelanX/SkyblockBuilder/files/9136286/skyblock.testing-horriblebadtime.zip)
Another update. Here is a version of the pack that loads my structures with the approrpiate config and all, still not generating structures

**Comment by MelanX** [comment] 2022-07-19 03:55
Do you know which mod causes this? Because I tested it with LibX, Skyblock Builder and Shrines Structures (or whatever the name is) together with your datapack and it generated fine. So, it needs to be an incompatibility or you have wrong biomes set for the structures. You said something about BoP. Maybe normal biomes are missing? I don’t know.
Please find out what’s the real problem and which mod causes this. Otherwise, I’m not able to fix this because I have to less free time to check whole modpacks to find incompatibility. Sorry, i really don’t have the time.

**Comment by tmanfoo1** [comment] 2022-07-19 03:57
> 

This is a the tiny version pack with the 5 mods necessary to cause issues! that should help you identify the problem!

Also will you be able to fix the lucky block issue?

**Comment by MelanX** [comment] 2022-07-19 04:00
Okay, didn’t look at it. Just woke up and thought I should tell you this that you could use the time while I’m at work.
lucky block: I don’t know.

**Comment by MelanX** [comment] 2022-07-19 04:01
Which lucky blocks mod do you use?

**Comment by tmanfoo1** [comment] 2022-07-19 04:13
> Okay, didn’t look at it. Just woke up and thought I should tell you this that you could use the time while I’m at work. lucky block: I don’t know.

believe it or not I am trying to make your life a tad easier!



> Which lucky blocks mod do you use?



> Which lucky blocks mod do you use?

lucky-block-forge-1.18.2-13.1.jar

**Comment by tmanfoo1** [comment] 2022-07-19 04:14
I appreciate your help and your patience. I am trying my best.

**Comment by tmanfoo1** [comment] 2022-07-19 04:34
so update!! the structures *do* spawn correctly now. [my minecraft client got corrupt or something. A friend was able to get it working] However the lucky blocks issue still exists!

**Comment by MelanX** [comment] 2022-07-19 04:40
So.. the only problem is Lucky Blocks now?

**Comment by tmanfoo1** [comment] 2022-07-19 04:45
actually I am sorry lol. I found out the real issue between me and some of my friends. The reason why the testing was inconclusive is due to some of us selecting the wrong starting island.

So in other words what is actually causing the crash is our starting island being specifically the andromeda and my datapack. For whatever reason they are not getting along well.
Is it possible that since I used the structure saver for the andromeda and normal structure blocks for my other structures it is causing issues? [I know when I tried to use structure saver nbt files in my datapack it crashed it]

Sorry for the confusion. But I found out at least what *exactly* is causing it

**Comment by tmanfoo1** [comment] 2022-07-19 04:50
then again I used your structure saver for the normal sized islands as well. It could be a size issue or something...?

**Comment by MelanX** [comment] 2022-07-19 05:02
Sorry but this issue is a mess. So many different issues combined in this one.
I now close this issue. Please open an issue for each problem you have.
Lucky Block stuff is one issue, the problem with your friend is one issue, and whatever else, I don’t get it anymore.
You can use blank issues for that, I now know your versions. Just a detailed description how to actually reproduce the problem with additional files if needed.

**Closed as completed by MelanX** 2022-07-19 05:02 UTC
Labels: bug
