### ISSUE TITLE
Datapack Structures

### ISSUE THREAD

**Issue by tmanfoo1** [MelanX/SkyblockBuilder#91] opened 2022-07-17 23:34 UTC
### Minecraft version

1.18.2

### LibX version

3.2.18

### Skyblock Builder version

3.3.22

### Forge version

40.1.55

### The latest.log file

[2022-07-17-6.log.gz](https://github.com/MelanX/SkyblockBuilder/files/9128767/2022-07-17-6.log.gz)

### Issue description

generation freezes on skyblock worlds with datapack selected

**Comment by tmanfoo1** [comment] 2022-07-18 00:10
[latest.log](https://github.com/MelanX/SkyblockBuilder/files/9128819/latest.log)
Here is the log ^
Another weird note is that for whatever reason it seems to generate fine in the log, but upon generating it just freezes at 100%

**Comment by tmanfoo1** [comment] 2022-07-18 00:16
[sky_isles.zip](https://github.com/MelanX/SkyblockBuilder/files/9128829/sky_isles.zip)
[skyblockbuilder.zip](https://github.com/MelanX/SkyblockBuilder/files/9128831/skyblockbuilder.zip)
if you wanna try for yourself

**Comment by MelanX** [comment] 2022-07-18 02:41
Will test later but for now:
1. Datapack stuff wasn’t tested on 1.18.2 properly, only on 1.19 (and it works fine there, so I hope it’s easy to fix in 1.18.2).
2. Did you try your Datapack in a normal world? If yes, what happened?
3. You could just allow all structures at once with `skyisles:*` as a wildcard.

**Comment by tmanfoo1** [comment] 2022-07-18 02:48
2) I did try it in 1.18.2 and yes it worked properly
3) No I did not thanks!

**Comment by tmanfoo1** [comment] 2022-07-18 02:53
also idk if it is notworthy or worthwile to mention but I got help with the dude from shrines structures to generate my structures. so they are reliant on their infrastructure

**Comment by tmanfoo1** [comment] 2022-07-18 03:07
also if you think you need the modpack I can provide a zip file

**Comment by MelanX** [comment] 2022-07-18 04:06
> also if you think you need the modpack I can provide a zip file

No, I don’t want other mods which could be the problem. I just want to know if my mod works fine or not.

**Comment by tmanfoo1** [comment] 2022-07-18 04:25
ok... well do you have any idea on the when/if this will be fixed?

**Comment by MelanX** [comment] 2022-07-18 04:29
I need to test it. This will probably happen today. Now, it is 6:29am. My full time job didn’t even start for today. After that, there are only a few hours until I go to bed. So, if not today, maybe tomorrow or within the next few days. And that’s only looking into the problem. Fixing is another issue and I can’t give a ETA.

**Comment by tmanfoo1** [comment] 2022-07-18 04:45
yikes... alright. This was the last thing we gotta do before releasing my new modpack x3
I will be patient

**Comment by MelanX** [comment] 2022-07-18 15:28
Can't reproduce. World loaded fine.
Here my mods:
![image](https://user-images.githubusercontent.com/26039509/179546779-21bb93bb-f6e0-4b41-8410-255cfecd0a80.png)

Used your config and your datapack to create the world.

**Comment by tmanfoo1** [comment] 2022-07-18 15:37
and you saw the structures actually generate?

**Comment by tmanfoo1** [comment] 2022-07-18 15:38
I will disable groups of mods until we can figure out which one is causing it to malfunction if so.

**Comment by tmanfoo1** [comment] 2022-07-18 15:39
and double checking you actually *got* into the world and you used my config for skyblock builder correct?

**Comment by tmanfoo1** [comment] 2022-07-18 15:42
also is it possible biomes o plenty is causing an issue? because my datapack is also dependent on biomes o plenty

**Comment by MelanX** [comment] 2022-07-18 16:05
> and you saw the structures actually generate?

Your problem was that it freezes at 100%. I checked only this.

> and double checking you actually _got_ into the world and you used my config for skyblock builder correct?

Yes.

> also is it possible biomes o plenty is causing an issue? because my datapack is also dependent on biomes o plenty

I don't know, never tried with BoP.

**Comment by tmanfoo1** [comment] 2022-07-18 16:57
would this work easier if I could find a way to turn my datapack into a mod?

**Comment by tmanfoo1** [comment] 2022-07-18 17:02
Also I am currently working on creating a modpack with the minimal amount of mods to create the glitch

**Comment by tmanfoo1** [comment] 2022-07-18 17:10
also would you like me to create a seperate ticket for the structures not generating at all?

**Comment by MelanX** [comment] 2022-07-18 17:40
This issue is fixed in the newest version. My Jenkins has a few problems and I need to fix them. This issue will be closed now, but the update will not be pushed now. I first need to fix the problems on my Jenkins because it builds and uploads my mods for me.

**Closed as completed by MelanX** 2022-07-18 17:40 UTC
Labels: bug
