### ISSUE TITLE
Shrines structure datapack freezing at 100%

### ISSUE THREAD

**Issue by tmanfoo1** [MelanX/SkyblockBuilder#95] opened 2022-07-19 05:11 UTC
Minecraft version
1.18.2

LibX version
3.2.18

Skyblock Builder version
3.3.23

Forge version
40.1.68

The latest.log file
[latest.log](https://github.com/MelanX/SkyblockBuilder/files/9136035/latest.log)

Issue description
The generation freezes at 100% if my own datapack is selected and the andromeda starting island is selected,
Note. It seems to not happen 100% of the time. About 25% of the time it gets to loading terrain, and about 5% of the time it actually gets into the world! This explains a lot of the confusion, and also makes my theory about structures overlapping with yours more possible

Steps to reproduce

navigate to world selector screen and ensure andromeda is selected

Ensure the datapack is properly loaded as well [ensure we have dependencies, which are biomes o plenty and shrines structures]

Upon generating a world you will notice you never fully get into the game

[skyblock testing-horriblebadtime.zip](https://github.com/MelanX/SkyblockBuilder/files/9136638/skyblock.testing-horriblebadtime.zip)

Other information
No response

**Comment by tmanfoo1** [comment] 2022-07-19 06:10
*note not sure if its possible but what if the structures are intersecting? that could cause issues

**Comment by tmanfoo1** [comment] 2022-07-19 13:42
Note. It seems to not happen 100% of the time. About 25% of the time it gets to loading terrain, and about 5% of the time it actually gets into the world! This explains a lot of the confusion, and also makes my theory about structures overlapping with yours more possible

**Comment by tmanfoo1** [comment] 2022-07-19 16:05
The Andromeda island [without lucky blocks installed] is also causing issues with generation. For whatever reason either the Andromeda sky block can be selected OR have my datapack installed. If both are installed it causes frequent freezing on generation

**Comment by MelanX** [comment] 2022-07-19 16:17
I can't reproduce this, sorry.
And I looked a bit at the files. The andromeda island is 6.89 MB! Wow! You will definitely have problems with that on a server. Or if Sky GUIs is installed. There will be issues with a structure that big.
And yes, some structures may be overlapping with the starting island... I mean... it's 186x163x85 blocks! That's a lot. I know, it probably was a lot of work to create it... I recommend finding a way to provide much smaller island.
And it's not freezing, it's generating the island.

**Comment by tmanfoo1** [comment] 2022-07-19 17:16
Well since thet can generate separately they should be able to work together. Is there a way tk dida le generation of structures in a radius around spawn?

**Comment by MelanX** [comment] 2022-07-19 17:24
No, not possible.

**Comment by tmanfoo1** [comment] 2022-07-19 17:34
Well that sucks. Is there a way to make thr Andromeda ovewrite other structures n cut em off? So it at least generate?

**Comment by tmanfoo1** [comment] 2022-07-19 17:38
Because I tested this without the other structures from the datapack and it worked fine... what if I add the datapack after the andromeda is generated?

**Comment by MelanX** [comment] 2022-07-19 18:34
I don't know what exactly happens when the structure overrides. Not sure which order is used for generating. But adding the datapack after it was generated should work I guess.

**Comment by tmanfoo1** [comment] 2022-07-19 18:56
Do you know of a mod that can make that happen? Or do I just make my users do so manually?

**Comment by MelanX** [comment] 2022-07-19 19:01
I don't think that any mod would do that because it's odd. I'm sorry, can't help with that.

**Comment by tmanfoo1** [comment] 2022-07-19 20:31
Hmm how about structure spawn in tools aside from the vanilla load structures?

**Comment by tmanfoo1** [comment] 2022-07-20 02:33
you know what is weird.... the andromeda loads fine if you select it as a starting island after you get into the world by changing the default island shape.... I wonder if there is a way to delay when it generates or something

**Comment by MelanX** [comment] 2022-07-20 03:54
> Hmm how about structure spawn in tools aside from the vanilla load structures?

I don’t understand.



> you know what is weird.... the andromeda loads fine if you select it as a starting island after you get into the world by changing the default island shape.... I wonder if there is a way to delay when it generates or something

I still have no idea what exactly is the overlap you talk about. Starting island overrides normal structures? That just happens. I can’t change it.

**Comment by tmanfoo1** [comment] 2022-07-20 04:04
It's not generating at spawn lol. But it does if I change the island shape to Andromeda and join a team

**Comment by tmanfoo1** [comment] 2022-07-20 04:04
Which I thought was weird and worth mentioning

**Comment by MelanX** [comment] 2022-07-20 04:07
Okay, then I quote myself: 
> And yes, some structures may be overlapping with the starting island... I mean... it's 186x163x85 blocks!

**Comment by tmanfoo1** [comment] 2022-07-20 04:08
But like... it's generating properly 100% of the time. And not like just part of a time like normal

**Comment by tmanfoo1** [comment] 2022-07-20 04:08
So your argument is invalid. They are different in some way ostensibly

**Comment by MelanX** [comment] 2022-07-20 04:10
If it’s "generating properly 100% of the time", I think it’s fine.

**Comment by tmanfoo1** [comment] 2022-07-20 04:11
But on startup it isnt...

**Comment by tmanfoo1** [comment] 2022-07-20 04:11
Thats the point I'm making

**Comment by MelanX** [comment] 2022-07-20 04:20
Maybe the structures just don’t generate at 0 ~ 0 (and around). Or it’s not 100% of the time but only the times you tested it.

**Comment by tmanfoo1** [comment] 2022-07-20 05:04
I mean I tested it like 10 times

**Comment by MelanX** [comment] 2022-07-20 14:54
I close this now because I'm not able to fix it nor is there any other problem here which I could fix.
For detailed answer to this issue, see my first comment from yesterday.

**Closed as completed by MelanX** 2022-07-20 14:54 UTC
