### ISSUE TITLE
serene seasons bug

### ISSUE THREAD

**Issue by Warbringer12** [MelanX/SkyblockBuilder#77] opened 2022-05-11 18:31 UTC
### Minecraft version

1.16.5

### LibX version

1.16.3-1.0.76

### Skyblock Builder version

1.16.4-1.6.14

### Forge version

1.16.5

### The latest.log file

https://pastebin.com/neKuM3JM

### Issue description

started up world and immediately crashed

### Other information

SereneSeasons-1.16.5-4.0.1.125-universal

**Comment by MelanX** [comment] 2022-05-11 18:43
Duplicate of #48 which is fixed in newer versions. In 1.16.x, the other mods could fix this issue as described here: https://github.com/MelanX/SkyblockBuilder/issues/48#issuecomment-946939305
If I would need to fix it, I had to make a lot of breaking changes, so this will not be fixed in this "old" version, sorry.

**Closed as completed by MelanX** 2022-05-11 18:43 UTC
Labels: bug
